# Jekyll
exclude: []
markdown: redcarpet

permalink: /blog/:year/:month/:day/:title/
tagline: Benjamin Herbert

navigation:
- text: Home
  url: /index.html
  iconclass: icon-home icon-white
  alt_url: /index.html
  layout: default
- text: Imressum
  url: /impressum.html
  layout: default